<?php 
$dictionary_array=array(

    /*
    |--------------------------------------------------------------------------
    | Pagination Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used by the paginator library to build
    | the simple pagination links. You are free to change them to anything
    | you want to customize your views to better match your application.
	|
	|
    |/********* Common Labels **********/
    
	
	
    'Clients' 			=> 'Clients',
    'Client_Info' 			=> 'Client Info',
    'Client_Type' 		=> 'Client Type',
    'Client' 			=> 'Client',
    'Add_Client'        => 'Add Client',
    'Add_Member'        => 'Add Member',
    'Update_Member' 	=> 'Update Member',
    'Client_Id' 		=> 'Client Id',
    'Client_ID' 		=> 'Client ID',
    'Client_Name' 		=> 'Client Name',
	'Client_List'		=> 'Client List',
	'Search_Clients'	=> 'Search Clients',	
	'View_Clients'		=> 'View Clients',	
	'Client_Account'	=> 'Client Account',	
	
	'Contact_Sort'		=> 'Contact Sort',	
	'Main_Contact'		=> 'Main Contact',	
	'Contact_Information'=> 'Contact Information',	
	
	'Debtor'			=> 'Debtor',
	'Debtors'			=> 'Debtors',
	'Search_Debtors'			=> 'Search Debtors',
	'Debtor_Info'		=> 'Debtor Info',
	'Debtor_List'		=> 'Debtor List',	
    'Debtor_br_List'	=> 'Debtor<br>List',
    'Debtor_Name' 		=> 'Debtor Name',
    'Update_Debtor' 	=> 'Update Debtor',
    'Debt_Balance' 		=> 'Debt Balance',
	
    'Customer_Name' 	=> 'Customer Name',
    'Cust' 				=> 'Cust',
	
    'Employer' 			=> 'Employer',
    'Employee' 			=> 'Employee',
    'EmpId' 			=> 'EmpId',
    'Emp_ID' 			=> 'Emp ID',
    'Emp_Name' 			=> 'Emp Name',  
    'Employer_Name' 	=> 'Employer Name',  
    'Employer_Address' 	=> 'Employer Address',  
    'Emp' 				=> 'Emp',  
    'Mngr' 				=> 'Mngr',  
	
    'Lead' 				=> 'Lead',
    'Leads' 			=> 'Leads',
    'Lead_Type' 		=> 'Lead Type',
    'LeadType' 			=> 'LeadType',
    'Engagement_Type' 	=> 'Engagement Type',
    'Potential_Customer'=> 'Potential Customer',
    'Prospect' 			=> 'Prospect',
	
    'User' 			=> 'User',
    'User_Name' 	=> 'User Name',
    'Current_User' 	=> 'Current User',
    'Name' 			=> 'Name',
    'First_Name' 	=> 'First Name',
    'Last_Name' 	=> 'Last Name',
    'Salutation' 	=> 'Salutation',
	
    'Individual' 	=> 'Individual',
    'INDIVIDUAL' 	=> 'INDIVIDUAL',
    'Business' 		=> 'Business',
    'BUSINESS' 		=> 'BUSINESS',
	
    'Company_Name' 	=> 'Company Name',  
    'Last_Files' 	=> 'Last Files',
    'Last_Activity' => 'Last Activity',
    'Files' 		=> 'Files',
	
	'Sales' 		=> 'Sales',
	'Sales_Person' 	=> 'Sales Person',
	
	
	'Event_Time' 	=> 'Event Time',
	'Event_Title' 	=> 'Event Title',
	'Event_Group' 	=> 'Event Group',
	'Event_Description' 	=> 'Event Description',
	'Add_Calendar_Event' 	=> 'Add Calendar Event',
	'Add_This_Event' 	=> 'Add This Event',
	
	
    'From_address' 			=> 'From address',
    'Email_Address' 			=> 'Email Address',
    'From_email_address' 	=> 'From email address',
	
	
    'Address' 		=> 'Address',
    'Default_Address' 		=> 'Default Address',
	'City_Province'	=> 'City / Province',
    'Country'	=> 'Country',
    'Phone' 		=> 'Phone',	
    'Phone_Info' 		=> 'Phone Info',	
    'Ph_No' 		=> 'Ph No',	
    'Email' 		=> 'Email',
    'Letter_Email' 		=> 'Letter/Email',
    'No_Mail' 		=> 'No Mail',
    'Send_Email' 		=> 'Send Email',
    'SMS' 			=> 'SMS',
    'Message' 			=> 'Message',
    'Call' 			=> 'Call',
    'Cal_User' 			=> 'Cal User',
    'Letter' 		=> 'Letter',
    'Print_Letter' 		=> 'Print Letter',
    'Letter_Sent' 		=> 'Letter Sent',
    'From' 			=> 'From',
    'To' 			=> 'To',
    'Deleted' 		=> 'Deleted',
    'Assign_To' 		=> 'Assign To',
    'Assigned' 		=> 'Assigned',
    'Assign' 		=> 'Assign',
    'Last_Assigned' => 'Last Assigned',
    'Total_Assigned'=> 'Total Assigned',
    'Appointments' 	=> 'Appointments',
    'Exclude' 		=> 'Exclude',
    'Notes' 		=> 'Notes',
    'Add_Note' 		=> 'Add Note',
    'Note' 			=> 'Note',
    'NType' 		=> 'NType',
    'Lock' 			=> 'Lock',
    'Reminders' 	=> 'Reminders',
    'Remind' 		=> 'Remind',
    'None' 			=> 'None',
    'view' 			=> 'view',
    'Settings' 		=> 'Settings',
    'Option' 		=> 'Option',
    'Permission' 	=> 'Permission',
    'is' 			=> 'is',
    'Ln' 			=> 'Ln',
    'Default' 		=> 'Default',
	
    'Activity' 		=> 'Activity',
    'Active' 		=> 'Active',
    'Completed' 	=> 'Completed',
    'File_Manager' 	=> 'File Manager',
	
    'Schedule_Cal' 	=> 'Schedule Cal',
		
    'USD' 		=> 'USD',
	
    'Amount' 		=> 'Amount',
    'Price' 		=> 'Price',
    'Org_Amount' 	=> 'Org. Amount',
    'Org_Amnt' 		=> 'Org. Amnt',
    'Balance' 		=> 'Balance',
    'Owing' 		=> 'Owing',
    'Amt_Owing' 	=> 'Amt Owing',
    'A_C_Balance' 	=> 'A/C Balance',
    'A_C_Type' 		=> 'A/C Type',
    'Revenue' 		=> 'Revenue',
    'Account' 		=> 'Account',
    'A_C_Status' 	=> 'A/C Status',
    'Account_Status'=> 'Account Status',
    'Update_A_C' 	=> 'Update A/C',
    'Payments' 		=> 'Payments',
    'Overdue' 		=> 'Overdue',
    'O_C_Amt' 		=> 'O.C.Amt',
    'Amt' 			=> 'Amt',
    'Pay_Type' 			=> 'Pay Type',
    'Pay_Method' 			=> 'Pay Method',
    'Pay_Amt' 			=> 'Pay Amt',
    'Commission' 		=> 'Commission',
    'Comm' 				=> 'Comm',
    'Comm_Amt' 			=> 'Comm Amt',
    'Comm_Amount' 		=> 'Comm Amount',
    'Comm_br_Amount' 	=> 'Comm<br>Amount',
    'Due' 			=> 'Due',
    'Dues' 			=> 'Dues',
    'Original' 		=> 'Original',
    'Fees' 			=> 'Fees',
    'Rate' 			=> 'Rate',
    'Bill' 			=> 'Bill',
    'Total' 		=> 'Total',
    'Sub_Total' 		=> 'Sub Total',
    'Gross_Total' 		=> 'Gross Total',
    'Grand_Total' 			=> 'Grand Total',
    'Add_Trans' 			=> 'Add Trans',	 
    'Comm_Rate' 			=> 'Comm_Rate',
    'Account_Statement' 	=> 'Account Statement',
    'Statement' 			=> 'Statement',
    'Principal_Amount' 		=> 'Principal Amount',
    'Interest_Admin_Fees' 	=> 'Interest/Admin Fees',
    'Interest_and_Fees' 	=> 'Interest &amp; Fees',
    'Account_Number' 		=> 'Account Number',
    'Paid_at_br_Client' 	=> 'Paid at<br>Client ',
    'Paid_at_br_Agency' 	=> 'Paid at<br>Agency ',
    'Total_br_Payments' 	=> 'Total<br>Payments',
    'From_Amount' 	=> 'From Amount',
    'To_Amount' 	=> 'To Amount',
    'Lower_Amount' 	=> 'Lower Amount',
    'Upper_Amount' 	=> 'Upper Amount',
    'Average_Price' 	=> 'Average Price',
    'TOTAL_CHARGES' 					=> 'TOTAL CHARGES',
    'Deductions' 					=> 'Deductions',
    'D2R_Promotion' => 'D2R Promotion',
    'USD_NET_TOTAL' => 'USD NET TOTAL',
    'CND_NET_TOTAL' => 'CND NET TOTAL',
	
	'Held' 					=> 'Held',
	'Agency' 				=> 'Agency',
	'Invoice' 				=> 'Invoice',
	'Invoice_Id' 			=> 'Invoice Id',
	'Edit_Invoice' 			=> 'Edit Invoice',
	'Create_Invoice' 		=> 'Create Invoice',
	'Create_Invoice' 		=> 'Create Invoice',
	'Add_Invoice' 			=> 'Add Invoice',
	'Invoice_Items' 		=> 'Invoice Items',
	'Invoice_List' 			=> 'Invoice List',
	'Invoice_Date' 			=> 'Invoice Date',
    'Inv_Cnt'				=> 'Inv Cnt',
    'Invoiced_To'			=> 'Invoiced To',
    'Paid_to'				=> 'Paid to',
	'Total_Invoices' 		=> 'Total Invoice(s)',
    'Dr' 					=> 'Dr',
    'Cr' 					=> 'Cr',
    'Comm_Dr' 				=> 'Comm Dr',
    'Comm_Cr' 				=> 'Comm Cr',
    'Calculate_Totals' 		=> 'Calculate Totals',
    'Invoice_Payments' 		=> 'Invoice Payments',
    'Payments_Invoiced' 	=> 'Payments Invoiced',
    'Payments_Posted' 		=> 'Payments Posted',
    'Related_Invoice' 		=> 'Related Invoice',
    'Total_Comm_Due' 		=> 'Total Comm. Due',
    'Total_Comm_Held' 		=> 'Total Comm. Held',
    'Total_Debts_Collected_at_Client' => 'Total Debts Collected at Client',
    'Total_Debts_Collected_at_Agency' => 'Total Debts Collected at Agency',
    'Commission_Earned_by_Agency' => 'Commission Earned by Agency',
    'Commission_Paid_From_Trust_Fund' => 'Commission Paid From Trust Fund',
	
    'Before' 		=> 'Before',
    'After' 		=> 'After',	
    'Grtr' 			=> 'Grtr',
    'Less' 			=> 'Less',
    'Previous' 		=> 'Previous',
    'Next' 			=> 'Next',
	'Start' 		=> 'Start',
	'Begin' 		=> 'Begin',
	'End' 			=> 'End',
    'Desc' 			=> 'Desc',
    'Asc' 			=> 'Asc',
    'Yes' 			=> 'Yes',
    'No' 			=> 'No',
    'Continue' 		=> 'Continue',
    'First' 		=> 'First',
    'Last' 			=> 'Last',
    'In' 			=> 'In',
    'Out' 			=> 'Out',
    'Check' 		=> 'Check',
    'Uncheck' 		=> 'Uncheck',
	
    'DOB' 			=> 'DOB', 
    'Date' 			=> 'Date', 
    'Crt_Date' 			=> 'Crt Date', 
    'Month' 			=> 'Month', 
    'Yr/Mon' 			=> 'Yr/Mon', 
    'Date_From' 		=> 'Date From', 
    'Date_To' 			=> 'Date To', 
    'Time_Period' 			=> 'Time Period', 
    'Select_Date' 			=> 'Select Date', 
    'Start_Date' 			=> 'Start Date', 
    'Start_Time' 			=> 'Start Time', 
    'End_Date' 			=> 'End Date', 
    'Dates' 			=> 'Dates', 
    'Choose_date' 			=> 'Choose date', 
    'Assigned_Date' => 'Assigned Date',
    'Default_Date' 	=> 'Default Date',
    'Date_Time' 	=> 'Date Time',
    'At_Start' 	=> 'At Start',
    '5_min' 	=> '5 min',
    '10_min' 	=> '10 min',
    '15_min' 	=> '15 min',
    '30_min' 	=> '30 min',
    '1_hour' 	=> '1 hour',
    'No_of_Day' 	=> 'No. of Day',
    'No_of_Week' 	=> 'No. of Week',
    'No_of_Month' 	=> 'No. of Month',
    'Created_Date' 	=> 'Created Date',
    'Age' 	=> 'Age',
    'Edit_br_Date' 	=> 'Edit<br>Date',
    'Create_Date' 	=> 'Create Date',
    'Duration(sec)' 	=> 'Duration(sec)',
    
		
    'Collect' 		=> 'Collect',		
    'Collector' 	=> 'Collector',	
    'Collected' 	=> 'Collected',	
    'Current_Collector' 	=> 'Current Collector',		
	
    'Credit_Bureau' => 'Credit Bureau',	
    'Bureau' 		=> 'Bureau',	
    'Bureau_Date' 		=> 'Bureau Date',	
    'EquiFax' 		=> 'EquiFax',	
    'Equifax' 		=> 'Equifax',	
    'Cr_Bru_2' 		=> 'Cr Bru 2',	
    'Bur_3' 		=> 'Bur 3',	
    'Bur_2' 		=> 'Bur 2',	
	
	'Print' 		=> 'Print',
	'Create' 		=> 'Create',
	'Insert' 		=> 'Insert',
    'Update' 		=> 'Update',	
    'Upd' 			=> 'Upd',	
    'New' 			=> 'New',	 
    'Add' 			=> 'Add',	 
    'ADD' 			=> 'ADD',	 
    'Added' 		=> 'Added',	 
    'Edit' 			=> 'Edit',	 
    'Rep' 			=> 'Rep',	 
    'edit' 			=> 'edit',	 
    'Cancel' 			=> 'Cancel',	 
    'Add_New' 		=> 'Add New',	 
    'Del' 			=> 'Del',	
    'Delete' 		=> 'Delete',
    'Search' 		=> 'Search',
    'Search_String' 		=> 'Search String',
    'Save' 			=> 'Save',	
    'Submit' 		=> 'Submit',
    'Download' 		=> 'Download',
    'Close' 		=> 'Close',
    'Saved' 		=> 'Saved',
    'Clear' 		=> 'Clear',
    'Reset' 		=> 'Reset',
    'Mod' 			=> 'Mod',
    'Row' 			=> 'Row',
    'Sel' 			=> 'Sel',
    'Get' 			=> 'Get',
    'Record' 			=> 'Record',
    'Direction' 		=> 'Direction',
    'Quantity' 			=> 'Quantity',
    'Dialer_Number' 	=> 'Dialer Number',
    'Dialer_Message' 	=> 'Dialer Message',
    'Dialer_Language' 	=> 'Dialer Language',
    'Choosen_List' 		=> 'Choosen List',
    'Add_Account' 		=> 'Add Account',
    'Add_Numbers' 		=> 'Add Numbers',
    'Edit_Number' 		=> 'Edit Number',
    'Add_Address' 		=> 'Add Address',
    'Edit_Address' 		=> 'Edit Address',
    'Add_Attachments' 	=> 'Add Attachments',
	
	
    'American_English' 	=> 'American English',	
    'Canadian_English' 	=> 'Canadian English',	
    'Australian_English'=> 'Australian English',	
    'Canada_French'		=> 'Canada French',	
    'France_French'		=> 'France French',	
	
	
    'General_Info' 		=> 'General Info',	
    'Title' 		=> 'Title',	
    'All' 			=> 'All', 	
    'ALL' 			=> 'ALL', 	
    'Code' 			=> 'Code',
    'All_records' 			=> 'All records',
    'POST_IT' 			=> 'POST IT',

    'File' 				=> 'File',
    'File_Number' 		=> 'File Number',
    'File_description' 	=> 'File description',
    'File_Status' 		=> 'File Status',
	
	
    'Help' 			=> 'Help',
    'Abrv' 			=> 'Abrv',
    'Status' 		=> 'Status',
    'AC_Status' 		=> 'AC Status',
    'Add_Debtor' 	=> 'Add Debtor',
    'Type' 			=> 'Type',
    
    'Method' 		=> 'Method',
    'Location' 		=> 'Location',
    'Locatn' 		=> 'Locatn',
    'ID' 			=> 'ID',
    'Mail_Flag' 	=> 'Mail Flag',
    
    'File_Count'	=> 'File Count',
    'Count'			=> 'Count',
    'List'			=> 'List',
    'List_Name'		=> 'List Name',
    'Save_List'		=> 'Save List',
    'Manage_Lists'		=> 'Manage Lists',
    'List_Description'	=> 'List Description',
    'Excl'			=> 'Excl',
    'of'			=> 'of',
    'On'			=> 'On',
    'History'		=> 'History',
    'Legal'			=> 'Legal',
    'Activities'	=> 'Activities',
    'Custom'		=> 'Custom',
    'Sort'			=> 'Sort',
    'Srt'			=> 'Srt',
    'Number'		=> 'Number',
    'Description'	=> 'Description',
    'Summary'		=> 'Summary',
    'Doc'			=> 'Doc',
    'Ref'			=> 'Ref',
    'Reference'		=> 'Reference',
    'Ref_Type'		=> 'Ref Type',
    'Ref_ID'		=> 'Ref ID',
    'Null'			=> 'Null',
    'Perm'			=> 'Perm',
    'Order'			=> 'Order',
    'Dialer'		=> 'Dialer',
    'SIC'			=> 'SIC',
    'Prt'			=> 'Prt',
    'Remaining'		=> 'Remaining',
    'Contacts'		=> 'Contacts',
    'Manager'		=> 'Manager',
    'Document'		=> 'Document',
    'Template'		=> 'Template',
    'Condition'		=> 'Condition',
    'Group'			=> 'Group',
    'Sequence'		=> 'Sequence',
    'Details'		=> 'Details',
    'Abbrev'		=> 'Abbrev',
    'Dialable'		=> 'Dialable',
    'Product'		=> 'Product',
    'Appt'			=> 'Appt',
    'Abbreviation'		=> 'Abbreviation',
    'Last_Files'		=> 'Last/Files',
    'Import_Source'		=> 'Import Source',
    'Refresh_Page'		=> 'Refresh Page',
    'View_and_Post'		=> 'View &amp; Post',	
    'Lists'				=> 'Lists',
    'Comm_Type'			=> 'Comm Type',
    'File_Ref_Number'	=> 'File/Ref Number',
    'Print_Samples'	=> 'Print Samples',
   
	

    'Campaign'				=> 'Campaign',
    'Campaign_Name'				=> 'Campaign Name',
    'Campaign_Description'	=> 'Campaign Description',
    'Campaign_Abrev'		=> 'Campaign Abrev',
    'Create_Campaign'		=> 'Create Campaign',
    'Campaign_List'			=> 'Campaign List',
    'Campaign_Steps'		=> 'Campaign Steps',
    'Campaign_Step'			=> 'Campaign Step',
    'View_Campaign_Logs'	=> 'View Campaign Logs',
    'Send_Date'				=> 'Send Date',
    'Mail_Subject'			=> 'Mail Subject',
    'Mail_Message'			=> 'Mail Message',
    'Mail_Id'				=> 'Mail Id',
	
	
	'Commission_Rate'		=> 'Commission Rate',
	'Rate_Plan_Levels'		=> 'Rate Plan Levels',
	'Rate_Plan_Level_Add'	=> 'Rate Plan Level Add',
	'Rate_Plan_Level_Update'=> 'Rate Plan Level Update',
	'View_Plan_Levels'		=> 'View Plan Levels',
	'Plan_Level_Type'		=> 'Plan Level Type',
	'Add_New_Level'			=> 'Add New Level',
	'Update_Rate_Plan'		=> 'Update Rate Plan',
	'PLAN' 					=> 'PLAN',
    'Plan' 					=> 'Plan',
    'Rate_Plan' 			=> 'Rate Plan',
    'Court_Order' 			=> 'Court Order',
    'Add_Rate_Plan' 		=> 'Add Rate Plan',
    'Plan_Sequence' 		=> 'Plan Sequence',
    'Plan_Commission_Type' 	=> 'Plan Commission Type',
    'one_Year_Over_Due_Flag' 		=> '(1) one Year Over Due Flag',
    'Level_Commission' 		=> 'Level Commission',
    'Level_Abbreviation' 	=> 'Level Abbreviation',
    'Level_Description' 	=> 'Level Description',
    'Level_Sort_Sequence' 	=> 'Level Sort Sequence',
    'Level_Start_Date' 		=> 'Level Start Date',
    'Level End Date' 		=> 'Level End Date',
    'Level_Start_Amount' 	=> 'Level Start Amount',
    'Level_Start_Amount' 	=> 'Level Start Amount',
    'Level_End_Amount' 		=> 'Level End Amount',
    'Court_Order_Flag' 		=> 'Court Order Flag',
    'Number_of_Days' 		=> 'Number of Days',
	
	
	'Account_Type' 					=> 'Account Type',
	'Acc Type' 						=> 'Acc Type',
    'Collection_Customer' 			=> 'Collection Customer',
    'Accounts_Receivable_Customer' 	=> 'Accounts Receivable Customer',
    'Lead_Cycle' 					=> 'Lead Cycle',
    '1Yr' 					=> '1Yr',
    'Crt' 					=> 'Crt',
    '3rd' 					=> '3rd',
    'Flat_Rate' 					=> 'Flat Rate',
	
	
    'Add_Receipt' 		=> 'Add Receipt',
    'Payment_Receipt' 	=> 'Payment Receipt',
    'Receipt_To' 		=> 'Receipt To',
    'Receipt_Date' 		=> 'Receipt Date',
    'Receipt_Item' 		=> 'Receipt Item',
	
	
    'Status_and_Activity'	=> 'Status and Activity',
    'Check_Availablity'		=> 'Check Availablity',
    'Select_Template'		=> 'Select Template',
    'Statement_of_Account'	=> 'Statement of Account',
	
    'Manage_Letters'		=> 'Manage Letters',
    'Add_New_Layout'		=> 'Add New Layout',
    'Select_Letter_Group'	=> 'Select Letter Group',
    'Display_Desc'	=> 'Display Desc.',
    'Last_Update'	=> 'Last Update',
    'Layout'		=> 'Layout',
    'Template_type'		=> 'Template type',
    'Select'			=> 'Select',
    'Field_Type'		=> 'Field Type',
    'Available_Fields'	=> 'Available Fields',
    'Full_Description'	=> 'Full Description',
    'Add_New_Letters'	=> 'Add New Letters',
    'Manage_Layouts'	=> 'Manage Layouts',
    'Select_Letter_Group'	=> 'Select Letter Group',
    'Query'				=> 'Query',
    'Sample'			=> 'Sample',
    'Dup'			=> 'Dup',
	
	'Calendar_Events_List' 	=> 'Calendar Events List',
	'Phone_Email_List' 		=> 'Phone Email List',
	'Auto_Dialer_List' 		=> 'Auto Dialer List',
	'Address_List'			=> 'Address List',
	'Custom_Fields_List' 	=> 'Custom Fields List',
	'Transaction_List' 		=> 'Transaction List',
	'Notes_List' 			=> 'Notes List',
	'Phone_List' 			=> 'Phone List',
	'Schedule_Debtor_Transaction' 	=> '<span style="color:red;">Schedule</span> Debtor Transaction',
	'Add_Debtor_Transaction' 	=> 'Add Debtor Transaction',
	
	
    'datatable_info' 				=> 'Showing _START_ to _END_ of _TOTAL_ entries', 	
    'datatable_info_empty' 			=> 'Showing 0 to 0 of 0 entries',	 
    'datatable_paginate_next' 		=> 'Next',	
    'datatable_paginate_previous' 	=> 'Previous',	
    'datatable_lengthMenu' 			=> 'Show _MENU_ entries',	
	
);


