<?php 
$dictionary_array=array(

    /*
    |--------------------------------------------------------------------------
    | Pagination Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used by the paginator library to build
    | the simple pagination links. You are free to change them to anything
    | you want to customize your views to better match your application.
	|
	|
    |/********* Common Labels **********/
    
	
	
    'Clients' 			=> 'Departments',
    'Client_Type' 			=> 'Department Type',
    'Client' 			=> 'Department',
    'Add_Client' 		=> 'Add Department',
    'Client_ID' 		=> 'Department ID',
    'Client_Name' 		=> 'Department Name',
	'Client_List'		=> 'Department List',
	'Search_Clients'	=> 'Search Departments',	
	'View_Clients'	=> 'View Departments',	
	
	'Debtor'		=> 'Student',
	'Debtor_List'	=> 'Student Debt List',	
    'Debtor_br_List'		=> 'Student<br>List',
    'Debtor_Name' 	=> 'Student Name',
    'Update_Debtor' 	=> 'Update Student',
    'Debt_Balance' 	=> 'Debt Balance',
	
    'Employer' 		=> 'Employer',
    'Employee' 		=> 'Employee',
    'EmpId' 		=> 'EmpId',
    'Emp_Name' 		=> 'Emp Name',  
    'Employer_Name' 		=> 'Employer Name',  
    'Employer_Address' 		=> 'Employer Address',  
    'Emp' 		=> 'Emp',  
    'Mngr' 		=> 'Mngr',  
	
    'Leads' 		=> 'Leads',
    'Lead_Type' 	=> 'Lead Type',
    'LeadType' 	=> 'LeadType',
    'Engagement_Type' 	=> 'Engagement Type',
	
    'User' 			=> 'User',
    'User_Name' 	=> 'User Name',
    'Current_User' 	=> 'Current User',
    'Name' 			=> 'Name',
    'First_Name' 	=> 'First Name',
    'Salutation' 	=> 'Salutation',
	
    'Individual' 	=> 'Individual',
    'Business' 		=> 'Business',
	
    'Company_Name' 	=> 'Company Name',  
    'Last_Files' 	=> 'Last Files',
    'Last_Activity' => 'Last Activity',
    'Files' 		=> 'Files',
	
	'Sales' 		=> 'Sales',
	'Sales_Person' 	=> 'Account Manager',
	
	
	'Event_Time' 	=> 'Event Time',
	'Event_Title' 	=> 'Event Title',
	'Event_Group' 	=> 'Event Group',
	'Event_Description' 	=> 'Event Description',
	'Add_Calendar_Event' 	=> 'Add Calendar Event',
	'Add_This_Event' 	=> 'Add This Event',
	
	
    'From_address' 			=> 'From address',
    'From_email_address' 	=> 'From email address',
	
	
    'Address' 		=> 'Address',
    'Default_Address' 		=> 'Default Address',
    'Phone' 		=> 'Phone',	
    'Phone Info' 		=> 'Phone Info',	
    'Email' 		=> 'Email',
    'No_Mail' 		=> 'No Mail',
    'Send_Email' 		=> 'Send Email',
    'SMS' 			=> 'SMS',
    'Call' 			=> 'Call',
    'Cal_User' 			=> 'Cal User',
    'Letter' 		=> 'Letter',
    'Print_Letter' 		=> 'Print Letter',
    'Letter_Sent' 		=> 'Letter Sent',
    'From' 			=> 'From',
    'To' 			=> 'To',
    'Deleted' 		=> 'Deleted',
    'Assign_To' 		=> 'Assign To',
    'Assigned' 		=> 'Assigned',
    'Assign' 		=> 'Assign',
    'Last_Assigned' => 'Last Assigned',
    'Total_Assigned'=> 'Total Assigned',
    'Appointments' 	=> 'Appointments',
    'Exclude' 		=> 'Exclude',
    'Notes' 		=> 'Notes',
    'Add_Note' 		=> 'Add Note',
    'Note' 			=> 'Note',
    'NType' 		=> 'NType',
    'Lock' 			=> 'Lock',
    'Reminders' 	=> 'Reminders',
    'Remind' 		=> 'Remind',
    'None' 			=> 'None',
    'view' 			=> 'view',
    'Settings' 		=> 'Settings',
    'Option' 		=> 'Option',
    'Permission' 	=> 'Permission',
    'is' 			=> 'is',
    'Default' 		=> 'Default',
	
    'Activity' 		=> 'Activity',
    'Active' 		=> 'Active',
    'Completed' 	=> 'Completed',
    'File_Manager' 	=> 'File Manager',
	
    'Schedule_Cal' 	=> 'Schedule Cal',
		
    'Amount' 		=> 'Amount',
    'Org_Amount' 	=> 'Org. Amount',
    'Balance' 		=> 'Balance',
    'Owing' 		=> 'Owing',
    'Amt_Owing' 		=> 'Amt Owing',
    'A_C_Balance' 	=> 'A/C Balance',
    'A_C_Type' 		=> 'A/C Type',
    'Revenue' 		=> 'Revenue',
    'Account' 		=> 'Account',
    'A_C_Status' 	=> 'A/C Status',
    'Account_Status'=> 'Account Status',
    'Update_A_C' 	=> 'Update A/C',
    'Payments' 		=> 'Payments',
    'Overdue' 		=> 'Overdue',
    'O_C_Amt' 		=> 'O.C.Amt',
    'Amt' 			=> 'Amt',
    'Pay_Amt' 			=> 'Pay Amt',
    'Comm' 			=> 'Comm',
    'Comm_Amt' 			=> 'Comm Amt',
    'Comm_Amount' 			=> 'Comm Amount',
    'Comm_br_Amount' 			=> 'Comm<br>Amount',
    'Due' 			=> 'Due',
    'Dues' 			=> 'Dues',
    'Original' 		=> 'Original',
    'Fees' 			=> 'Interest/Fees',
    'Rate' 			=> 'Rate',
    'Bill' 			=> 'Bill',
    'Total' 	=> 'Total',
    'Add_Receipt' 			=> 'Add Receipt',
    'Add_Trans' 			=> 'Add Trans',	 
    'Comm_Rate' 			=> 'Comm_Rate',
    'Account_Statement' 	=> 'Account Statement',
    'Rate_Plan' 			=> 'Rate Plan',
    'Statement' 			=> 'Statement',
    'Principal_Amount' 		=> 'Principal Amount',
    'Interest_Admin_Fees' 	=> 'Interest/Admin Fees',
    'Interest_and_Fees' 	=> 'Interest &amp; Fees',
    'Account_Number' 	=> 'Account Number',
    'Paid_at_br_Client' 	=> 'Paid at<br>Department ',
    'Paid_at_br_Agency' 	=> 'Paid at<br>Agency ',
    'Total_br_Payments' 	=> 'Total<br>Payments',
	
	'Invoice' 			=> 'Invoice',
	'Invoice_List' 		=> 'Invoice List',
	'Total_Invoices' 	=> 'Total Invoice(s)',
    'Dr' 				=> 'Dr',
    'Cr' 				=> 'Cr',
    'Comm_Dr' 			=> 'Comm Dr',
    'Comm_Cr' 			=> 'Comm Cr',
    'Payment_Receipt' 	=> 'Payment Receipt',
    'Invoice Payments' 	=> 'Invoice Payments',
	
    'Before' 		=> 'Before',
    'After' 		=> 'After',	
    'Grtr' 			=> 'Grtr',
    'Less' 			=> 'Less',
    'Previous' 		=> 'Previous',
    'Next' 			=> 'Next',
	'Start' 		=> 'Start',
	'End' 			=> 'End',
    'Desc' 			=> 'Desc',
    'Asc' 			=> 'Asc',
	
    'DOB' 			=> 'DOB', 
    'Date' 			=> 'Date', 
    'Date_From' 		=> 'Date From', 
    'Date_To' 			=> 'Date To', 
    'Select_Date' 			=> 'Select Date', 
    'Start_Date' 			=> 'Start Date', 
    'End_Date' 			=> 'End Date', 
    'Dates' 			=> 'Dates', 
    'Choose_date' 			=> 'Choose date', 
    'Assigned_Date' => 'Assigned Date',
    'Default_Date' 	=> 'Default Date',
    'Date_Time' 	=> 'Date Time',
    'At_Start' 	=> 'At Start',
    '5_min' 	=> '5 min',
    '10_min' 	=> '10 min',
    '15_min' 	=> '15 min',
    '30_min' 	=> '30 min',
    '1_hour' 	=> '1 hour',
    
		
    'Collect' 		=> 'Collect',		
    'Collector' 	=> 'Collector',	
    'Collected' 	=> 'Collected',	
    'Current_Collector' 	=> 'Current Collector',	
	
    'Credit_Bureau' => 'Credit Bureau',	
    'Bureau' 		=> 'Bureau',	
    'Bureau_Date' 		=> 'Bureau Date',	
    'EquiFax' 		=> 'EquiFax',	
    'Equifax' 		=> 'Equifax',	
    'Cr_Bru_2' 		=> 'Cr Bru 2',	
    'Bur_3' 		=> 'Bur 3',	
    'Bur_2' 		=> 'Bur 2',	
	
	'Print' 		=> 'Print',
	'Create' 		=> 'Create',
	'Insert' 		=> 'Insert',
    'Update' 		=> 'Update',	
    'New' 			=> 'New',	 
    'Add' 			=> 'Add',	 
    'ADD' 			=> 'ADD',	 
    'Added' 		=> 'Added',	 
    'Edit' 			=> 'Edit',	 
    'Rep' 			=> 'Rep',	 
    'edit' 			=> 'edit',	 
    'Cancel' 			=> 'Cancel',	 
    'Add_New' 		=> 'Add New',	 
    'Del' 			=> 'Del',	
    'Delete' 		=> 'Delete',
    'Search' 		=> 'Search',
    'Save' 			=> 'Save',	
    'Submit' 		=> 'Submit',
    'Download' 		=> 'Download',
    'Close' 		=> 'Close',
    'Saved' 		=> 'Saved',
    'Clear' 		=> 'Clear',
    'Reset' 		=> 'Reset',
    'Mod' 		=> 'Mod',
    'Add_Numbers' 		=> 'Add Numbers',
    'Edit_Number' 		=> 'Edit Number',
    'Add_Address' 		=> 'Add Address',
    'Edit_Address' 		=> 'Edit Address',
    'Add_Attachments' 	=> 'Add Attachments',
	
    'General_Info' 		=> 'General Info',	
    'Title' 		=> 'Message',	
    'All' 			=> 'All', 	
    'ALL' 			=> 'ALL', 	
    'Code' 			=> 'Code',
    'POST_IT' 			=> 'POST IT',

    'File' 				=> 'File',
    'File_Number' 		=> 'File Number',
    'File_description' 	=> 'File description',
    'File_Status' 		=> 'File Status',
	
	
    'Help' 			=> 'Help',
    'Abrv' 			=> 'Abrv',
    'Status' 		=> 'Status',
    'AC_Status' 		=> 'AC Status',
    'Add_Debtor' 	=> 'Add Student',
    'Type' 			=> 'Type',
    'Account_Type' 	=> 'Account Type',
    'Method' 		=> 'Method',
    'Location' 		=> 'Location',
    'Locatn' 		=> 'Locatn',
    'ID' 			=> 'ID',
    'Mail_Flag' 	=> 'Mail Flag',
    'PLAN' 			=> 'PLAN',
    'Plan' 			=> 'Plan',
    'File_Count'	=> 'File Count',
    'Count'			=> 'Count',
    'List'			=> 'List',
    'of'			=> 'of',
    'On'			=> 'On',
    'History'		=> 'History',
    'Legal'			=> 'Legal',
    'Activities'	=> 'Activities',
    'Custom'		=> 'Custom',
    'Sort'			=> 'Sort',
    'Number'		=> 'Number',
    'Description'	=> 'Description',
    'Inv_Cnt'		=> 'Inv Cnt',
    'Doc'			=> 'Doc',
    'Ref'			=> 'Ref',
    'Reference'		=> 'Reference',
    'Perm'			=> 'Perm',
    'Order'			=> 'Order',
    'Dialer'		=> 'Dialer',
    'SIC'			=> 'SIC',
    'Prt'			=> 'Prt',
    'Remaining'		=> 'Remaining',
    'Contacts'		=> 'Contacts',
    'Manager'		=> 'Manager',
    'Document'		=> 'Document',
    'Last_Files'		=> 'Last/Files',
    'Import_Source'		=> 'Import Source',
    'Refresh_Page'		=> 'Refresh Page',
    'View_and_Post'			=> 'View &amp; Post',	
    'Lists'			=> 'Lists',
    'Comm_Type'			=> 'Comm Type',
	

    'View_Campaign_Logs'			=> 'View Campaign Logs',
	
	
    'Status_and_Activity'	=> 'Status and Activity',
    'Check_Availablity'		=> 'Check Availablity',
    'Select_Template'		=> 'Select Template',
    'Statement_of_Account'		=> 'Statement of Account',
	
	'Calendar_Events_List' 	=> 'Calendar Events List',
	'Phone_Email_List' 		=> 'Phone Email List',
	'Auto_Dialer_List' 		=> 'Auto Dialer List',
	'Address_List'			=> 'Address List',
	'Custom_Fields_List' 	=> 'Custom Fields List',
	'Transaction_List' 	=> 'Transaction List',
	'Notes_List' 	=> 'Notes List',
	'Schedule_Debtor_Transaction' 	=> '<span style="color:red;">Schedule</span> Debt Transaction',
	'Add_Debtor_Transaction' 	=> 'Add Debt Transaction',
	
	
    'datatable_info' 				=> 'Showing _START_ to _END_ of _TOTAL_ entries', 	
    'datatable_info_empty' 			=> 'Showing 0 to 0 of 0 entries',	 
    'datatable_paginate_next' 		=> 'Next',	
    'datatable_paginate_previous' 	=> 'Previous',	
    'datatable_lengthMenu' 			=> 'Show _MENU_ entries',	
	
);


